
### CREATE MARKET DATA FUNCTIONS TO OBTAIN THE BELOW AUTOMATICALLY ###

# Spot symbol from Binance 
binance_symbol: XMRUSDT
binance_tick_size: 0.01
binance_lot_size: 0.01 

# Futures symbol from Bybit
bybit_symbol: XMRUSDT
bybit_tick_size: 0.05
bybit_lot_size: 0.01

# Primary data feed (BYBIT or BINANCE) 
# Check README.md for more info regarding this 
primary_data_feed: BINANCE

# A multiple of the tick size
# Prevents a 'ping-pong' effect
buffer: 3

# Account info ($)
account_size: 100

# Settings for volatility indicator 
bollinger_band_length: 20
bollinger_band_std: 5

# Master offsets 
quote_offset: +0.0 # Changes quote price in base units
size_offset: +0.0  # Changes quote size in quote units
volatility_offset: +0.0 # Changes quote range in base units

# Settings for Market Maker function 
base_spread: 0.1 # In quote asset unit
number_of_orders: 10 # Total number of orders
min_order_size: 0.1  # In base asset unit
max_order_size: 0.45  # In base asset unit

# Extreme value for inventory
# Check README.md for more info regarding this 
inventory_extreme: 0.5
